# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on: 
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  prepare_python:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
          architecture: 'x64'
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Display Python path
        run: where python
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          
  cmake:
    runs-on: windows-latest
    needs: prepare_python
    steps:
      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.8
        with:
          cmake-version: '3.16.x'
      - name: Use cmake
        run: cmake --version
        
  build:
    runs-on: windows-latest
    needs: prepare_python
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
